Repository GDSC-snowflowerthon/tumblog-team09-server, pull requests merged in 2024-01, with the labels that each got.

#6 [feature/2-addTumble] 텀블 등록 API
  src/main/java/snowflake/tumblog/common/BaseResponseStatus.java
  src/main/java/snowflake/tumblog/common/Constant.java
  src/main/java/snowflake/tumblog/tumble/controller/TumbleController.java
  src/main/java/snowflake/tumblog/tumble/domain/Size.java
  src/main/java/snowflake/tumblog/tumble/domain/Tumble.java
  src/main/java/snowflake/tumblog/tumble/dto/PostTumbleReq.java
  src/main/java/snowflake/tumblog/tumble/repository/TumbleRepository.java
  src/main/java/snowflake/tumblog/tumble/service/TumbleService.java
  src/main/java/snowflake/tumblog/user/domain/User.java
  src/main/java/snowflake/tumblog/user/domain/repository/UserRepository.java
Labels: ✨ feature

#11 [feature/9-getTumble] 텀블 상세 조회 API
  .gitignore
  src/main/java/snowflake/tumblog/common/enums/BaseResponseStatus.java
  src/main/java/snowflake/tumblog/tumble/controller/TumbleController.java
  src/main/java/snowflake/tumblog/tumble/domain/Tumble.java
  src/main/java/snowflake/tumblog/tumble/dto/GetTumbleResponse.java
  src/main/java/snowflake/tumblog/tumble/dto/PostTumbleRequest.java
  src/main/java/snowflake/tumblog/tumble/repository/TumbleRepository.java
  src/main/java/snowflake/tumblog/tumble/service/TumbleService.java
  src/main/resources/application.properties
Labels: ✨ feature

#13 [infra/12-webConfig] WebConfig 설정
  src/main/java/snowflake/tumblog/common/config/WebConfig.java
Labels: ⚙️ infra

#15 [Feature/8 chatgpt] ChatGpt API 기능 구현
  build.gradle
  src/main/java/snowflake/tumblog/chat/domain/ChatProperties.java
  src/main/java/snowflake/tumblog/chat/dto/ChatGptRequest.java
  src/main/java/snowflake/tumblog/chat/dto/ChatGptResponse.java
  src/main/java/snowflake/tumblog/chat/infrastructure/ChatConfig.java
  src/main/java/snowflake/tumblog/chat/service/ChatService.java
  src/main/java/snowflake/tumblog/ocr/presentation/OcrController.java
  src/main/java/snowflake/tumblog/ocr/service/OcrService.java
  src/main/resources/application.properties
  src/test/java/snowflake/tumblog/ocr/service/OcrServiceTest.java
  src/test/java/snowflake/tumblog/user/service/UserServiceTest.java
Labels: ✨ feature

#22 [dev] main merge
  .gitignore
  build.gradle
  src/main/java/snowflake/tumblog/chat/domain/ChatProperties.java
  src/main/java/snowflake/tumblog/chat/dto/ChatGptRequest.java
  src/main/java/snowflake/tumblog/chat/dto/ChatGptResponse.java
  src/main/java/snowflake/tumblog/chat/infrastructure/ChatConfig.java
  src/main/java/snowflake/tumblog/chat/service/ChatService.java
  src/main/java/snowflake/tumblog/common/BaseEntity.java
  src/main/java/snowflake/tumblog/common/BaseException.java
  src/main/java/snowflake/tumblog/common/BaseResponse.java
  src/main/java/snowflake/tumblog/common/config/AmazonS3Config.java
  src/main/java/snowflake/tumblog/common/config/SwaggerConfig.java
  src/main/java/snowflake/tumblog/common/config/WebConfig.java
  src/main/java/snowflake/tumblog/common/constants/Constant.java
  src/main/java/snowflake/tumblog/common/constants/RequestURI.java
  src/main/java/snowflake/tumblog/common/enums/BaseResponseStatus.java
  src/main/java/snowflake/tumblog/common/s3/controller/ImageController.java
  src/main/java/snowflake/tumblog/common/s3/service/ImageService.java
  src/main/java/snowflake/tumblog/ocr/domain/OcrProperties.java
  src/main/java/snowflake/tumblog/ocr/dto/CheckImageRequest.java
  src/main/java/snowflake/tumblog/ocr/dto/OcrRequest.java
  src/main/java/snowflake/tumblog/ocr/dto/OcrResponse.java
  src/main/java/snowflake/tumblog/ocr/presentation/OcrController.java
  src/main/java/snowflake/tumblog/ocr/service/OcrService.java
  src/main/java/snowflake/tumblog/tumble/domain/Size.java
  src/main/java/snowflake/tumblog/tumble/domain/Tumble.java
  src/main/java/snowflake/tumblog/tumble/domain/Tumbles.java
  src/main/java/snowflake/tumblog/tumble/dto/CreateTumbleRequest.java
  src/main/java/snowflake/tumblog/tumble/dto/TumbleDetailResponse.java
  src/main/java/snowflake/tumblog/tumble/presentation/TumbleController.java
  src/main/java/snowflake/tumblog/tumble/repository/TumbleRepository.java
  src/main/java/snowflake/tumblog/tumble/service/TumbleService.java
  src/main/java/snowflake/tumblog/user/domain/ExperiencePoint.java
  src/main/java/snowflake/tumblog/user/domain/Level.java
  src/main/java/snowflake/tumblog/user/domain/User.java
  src/main/java/snowflake/tumblog/user/domain/repository/UserAdapter.java
  src/main/java/snowflake/tumblog/user/domain/repository/UserPort.java
  src/main/java/snowflake/tumblog/user/domain/repository/UserRepository.java
  src/main/java/snowflake/tumblog/user/dto/CreateUserRequest.java
  src/main/java/snowflake/tumblog/user/dto/HomeResponse.java
  src/main/java/snowflake/tumblog/user/dto/MyPageResponse.java
  src/main/java/snowflake/tumblog/user/dto/UpdateUserRequest.java
  src/main/java/snowflake/tumblog/user/presentation/UserController.java
  src/main/java/snowflake/tumblog/user/service/UserService.java
  src/main/resources/application.properties
  src/test/java/snowflake/tumblog/TumblogApplicationTests.java
  src/test/java/snowflake/tumblog/ocr/service/OcrServiceTest.java
  src/test/java/snowflake/tumblog/tumble/service/TumbleServiceTest.java
  src/test/java/snowflake/tumblog/user/domain/UserTest.java
  src/test/java/snowflake/tumblog/user/service/UserServiceTest.java
Labels: 🛠️ CI/CD
